-
  name: 'Login Link'
  uriPattern: 'login'
  defaults:
    '@package':    'T3DD.Login'
    '@controller': 'Authentication'
    '@action':     'login'

-
  name: 'SSO Callback'
  uriPattern: 'sso'
  defaults:
    '@package':    'T3DD.Login'
    '@controller': 'Authentication'
    '@action':     'authenticate'