-
  name: 'SSO Parent Window Callback'
  uriPattern: 'sso/login'
  defaults:
    '@package':    'T3DD.Login'
    '@controller': 'AnonymousAuthentication'
    '@action':     'login'

-
  name: 'SSO Logout'
  uriPattern: 'sso/logout'
  defaults:
    '@package':    'T3DD.Login'
    '@controller': 'AnonymousAuthentication'
    '@action':     'logout'

-
  name: 'User Status'
  uriPattern: 'sso/status'
  defaults:
    '@package':    'T3DD.Login'
    '@controller': 'AnonymousAuthentication'
    '@action':     'status'
    '@format':     'json'

-
  name: 'SSO Parent Window Callback'
  uriPattern: 'sso/callback/{requestID}'
  defaults:
    '@package':    'T3DD.Login'
    '@controller': 'AnonymousAuthentication'
    '@action':     'callback'
    '@format':     'html'

-
  name: 'SSO Callback'
  uriPattern: 'sso'
  defaults:
    '@package':    'T3DD.Login'
    '@controller': 'AnonymousAuthentication'
    '@action':     'authenticate'