TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: atLeastOneToken
        providers:
          # configure SSO key to use
          Typo3OrgSsoProvider:
            provider: 'T3DD\Login\Security\Authentication\Provider\Typo3OrgSsoProvider'
            providerOptions:
              rsaKeyUuid: '6c9785b514e93c6467d4d74dff4a7455'