#                                                                        #
# Default routes configuration for the T3DD.Backend package              #
#                                                                        #

-
  name: 'Single Participant'
  uriPattern: 'api/participants/{participant}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Participant'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'PUT', 'DELETE']

-
  name: 'Participant list'
  uriPattern: 'api/participants'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Participant'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'POST']

-
  name: 'Single Session'
  uriPattern: 'sessions/{session}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Session'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'PUT', 'DELETE']
  routeParts:
    session:
      objectType: T3DD\Backend\Domain\Model\Session
-
  name: 'Single Session'
  uriPattern: 'sessions/edit/{session}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Session'
    '@action':     'edit'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET']
  routeParts:
    session:
      objectType: T3DD\Backend\Domain\Model\Session

-
  name: 'Session list'
  uriPattern: 'sessions'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Session'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'POST']

-
  name: 'Session votes'
  uriPattern: 'vote/{session}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Vote'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['POST', 'DELETE']
  routeParts:
    session:
      objectType: T3DD\Backend\Domain\Model\Session

-
  name: 'My votes'
  uriPattern: 'votes/me'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Vote'
    '@action':     'myVotes'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']

-
  name: 'Vote list'
  uriPattern: 'votes'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Vote'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']

-
  name: 'Single Value'
  uriPattern: 'values/{value}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Value'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'PUT', 'DELETE']
  routeParts:
    value:
      objectType: T3DD\Backend\Domain\Model\Value

-
  name: 'Value list'
  uriPattern: 'values'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Value'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'POST']
