#                                                                        #
# Default routes configuration for the T3DD.Backend package              #
#                                                                        #

-
  name: 'Participant api'
  uriPattern: 'api/participants/{participant}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Participant'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'PUT', 'DELETE']

-
  name: 'Participants api'
  uriPattern: 'api/participants'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Participant'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'POST']

-
  name: 'Sessions api'
  uriPattern: 'sessions/{session}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Session'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'PUT', 'DELETE']

-
  name: 'Sessions api'
  uriPattern: 'sessions'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Session'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['HEAD', 'GET', 'POST']

-
  name: 'Vote api'
  uriPattern: 'api/vote/{session}'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Vote'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['POST', 'DELETE']

-
  name: 'Vote api'
  uriPattern: 'api/votes/me'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Vote'
    '@action':     'myVotes'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']

-
  name: 'Vote api'
  uriPattern: 'api/votes'
  defaults:
    '@package':    'T3DD.Backend'
    '@controller': 'Vote'
    '@action':     'index'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']