T3DD:
  Backend:
    Registration:
      Bookable:
        Room:
          fractionBase: 12
          availableQuota: 62
        Ticket:
          availableQuota: 180
      Mail:
        Sender:
          name: 'TYPO3 Developer Days 2015'
          email: 't3dd15@typo3.org'
        Subjects:
          default: 'TYPO3 Developer Days 2015 Message'
          registrationCompleted: 'Registration for TYPO3 Developer Days 2015'
          participantCompleteRegistration: 'Update your registration for TYPO3 Developer Days 2015'