T3DD:
  Backend:
    Registration:
      Bookable:
        Room:
          fractionBase: 12
          availableQuota: 58
        Ticket:
          availableQuota: 204
      Mail:
        Sender:
          name: 'TYPO3 Developer Days 2015'
          email: 't3dd@typo3.org'
        Subjects:
          default: 'TYPO3 Developer Days 2015 Message'
          registrationCompleted: 'Registration for TYPO3 Developer Days 2015'
          participantCompleteRegistration: 'Update your participant details'
          moveToWaitingList: 'Ticket or room status for your registration has changed'

TYPO3:
  Flow:
    http:
      baseUri: 'https://t3dd15.typo3.org/'