-
  name: 'T3DD.Frontend'
  uriPattern: '<T3DDFrontendSubroutes>'
  subRoutes:
    'T3DDFrontendSubroutes':
      package: 'T3DD.Frontend'
      variables:
        'defaultUriSuffix': ''

-
  name: 'T3DD.Backend'
  uriPattern: '<T3DDBackendSubroutes>'
  subRoutes:
    'T3DDBackendSubroutes':
      package: 'T3DD.Backend'
      variables:
        'defaultUriSuffix': ''

-
  name: 'T3DD.Login'
  uriPattern: '<T3DDLoginSubroutes>'
  subRoutes:
    'T3DDLoginSubroutes':
      package: 'T3DD.Login'
      variables:
        'defaultUriSuffix': ''

-
  name: 'T3DD.Frontend'
  uriPattern: '<T3DDFrontendSubroutes>'
  subRoutes:
    'T3DDFrontendSubroutes':
      package: 'T3DD.Frontend'
      variables:
        'defaultUriSuffix': ''