-
  name: 'T3DD.Backend'
  uriPattern: '<T3DDBackendSubroutes>'
  subRoutes:
    'T3DDBackendSubroutes':
      package: 'T3DD.Backend'
      variables:
        'defaultUriSuffix': ''

-
  name: 'Flow'
  uriPattern: '<FlowSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FlowSubroutes:
      package: TYPO3.Flow
