T3DD:
  Login:
    ssoURL: 'https://typo3.org/my-account/sso/t3dd15/'
TYPO3:
  Flow:
    object:
      excludeClasses:
       'Networkteam.SentryClient': ['Networkteam\\SentryClient\\Aspect\\TypoScriptHandlerAspect']
