-
  name:  'T3DD Frontend'
  uriPattern: '{route}'
  defaults:
    '@package':    'T3DD.Frontend'
    '@controller': 'Frontend'
    '@action':     'serve'
    '@format':     'html'
  httpMethods: ['HEAD', 'GET']
  routeParts:
    route:
      handler:     'T3DD\Frontend\Routing\AppRouteHandler'